package com.wanted.entities;

/**
 * Created by xlin2 on 2015/11/13.
 */
public enum Information {
    REGISTER, LOGIN, UPDATE_USER, UPDATE_COMPANY, GET_COMPANY, GET_PEOPLE, GET_POST, RESUME,
    ADD_POST, ADD_FOLLOW, GET_FOLLOWING, GET_FOLLOWER, ADD_CONNECT, GET_LIKE, GET_APPLY,
    SUCCESS, FAIL, USER_EXIST, USER_NOT_EXIST, WRONG_PWD
}
